files:
  - source: /extension/en/messages.json
    translation: /extension/%two_letters_code%/%original_file_name%

  - source: /website/**/en.json
    translation: /website/**/%two_letters_code%.json
